shared:
  image: node:12
  steps:
    - step1: 'echo "Region: $(meta get parameters.name.value)"'
    
parameters:
  name: "wahapo"
  param1:
    value: "value1"
    description: "description of nameB"
  param2: ["value2-1", "value2-2"]
  paramA: "valueA"
  paramB: "valueB"
  paramC: "valueC"
  paramD: "valueD"
  paramE: "valueE"

jobs:
  main:
    requires: [~pr, ~commit]
